# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61c4df53d0fa51de77ddef495ebd751bdb8dd8043e70abef7ebf126f1faf4759f0b6454f57694b7769f76c4440b4f750788c4ab12fff05d9a28bd347a817df36

test:
  secret_key_base: 599aa326a27fe3a2eba44379aca2da1784465a38ae804bca88b39197b26f89990433b721abd92fb94f22f4f39772c850b7d1cafb7ec149baa5388be17127ff71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
